### ISSUE TITLE
[Test] Add nested polaris server for PolarisRegistryTest 

### ISSUE THREAD

**Issue by mroccyen** [polarismesh/femas#182]
![image](https://user-images.githubusercontent.com/22514893/176645300-7e6e77da-0253-4465-8095-384689c48137.png)

PolarisRegistryTest 单元测试跑不通，我觉得可以在单元测试中内置一个polaris服务器来处理注册与发现

**Comment by huyuanxin** [comment]
Unit test is provide for Github actions so that developer can make sure registry module work correctly.
If you wanna test module locally, please make sure middware is running
You can add my wechat: huyuanxin1999, if you hava any question

**Comment by mroccyen** [comment]
> Unit test is provide for Github actions so that developer can make sure registry module work correctly. If you wanna test module locally, please make sure middware is running You can add my wechat: huyuanxin1999, if you hava any question

@huyuanxin 这可能导致贡献者提交的代码的CI通过不了，CI运行单元测试的时候，就会报错

**Comment by mroccyen** [comment]
> Unit test is provide for Github actions so that developer can make sure registry module work correctly. If you wanna test module locally, please make sure middware is running You can add my wechat: huyuanxin1999, if you hava any question

![image](https://user-images.githubusercontent.com/22514893/179348734-3550fb9d-d51f-4cbd-bf1d-dfc6c8a1c668.png)

@huyuanxin 如图所示，这是CI给的TEST的错误

**Comment by huyuanxin** [comment]
please put actions link, this action failed because there is something wrong with the code

在 2022年7月16日，17:16，mroccyen ***@***.***> 写道：

﻿

Unit test is provide for Github actions so that developer can make sure registry module work correctly. If you wanna test module locally, please make sure middware is running You can add my wechat: huyuanxin1999, if you hava any question

[image]<https://user-images.githubusercontent.com/22514893/179348734-3550fb9d-d51f-4cbd-bf1d-dfc6c8a1c668.png>

@huyuanxin<https://github.com/huyuanxin> 如图所示，这是CI给的TEST的错误

**Comment by mroccyen** [comment]
> 

这个图片的PR只是修改了一些代码的格式，并没做任何逻辑修改

**Comment by huyuanxin** [comment]
如果你是在本地运行单元测试，是需要自行安装对应的注册中心的。
如果是在GitHub Actions运行单元测试，运行的脚本会自动配置最新的注册中心镜像。
看图中的代码，你是把sleep函数去除了，这个在GitHub Actions里面是可能出现问题的，可能存在注册或反注册已经完成，但注册发现拿到的信息还未更新。

**Comment by mroccyen** [comment]
> 如果你是在本地运行单元测试，是需要自行安装对应的注册中心的。 如果是在GitHub Actions运行单元测试，运行的脚本会自动配置最新的注册中心镜像。 看图中的代码，你是把sleep函数去除了，这个在GitHub Actions里面是可能出现问题的，可能存在注册或反注册已经完成，但注册发现拿到的信息还未更新。

图中错误信息来自 #177 ，并没有删除sleep函数

**Comment by huyuanxin** [comment]
你这个时候提交的代码是还没有sleep的，是我后来加的
